backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "real_images"
    label: "Real Images"
    folder: "uploads/real-images"
    create: true
    slug: "{{filename}}"
    media_folder: "assets/real-images"
    public_folder: "/assets/real-images"
    fields:
      - { label: "Image", name: "file", widget: "image" }

  - name: "ai_images"
    label: "AI Images"
    folder: "uploads/ai-images"
    create: true
    slug: "{{filename}}"
    media_folder: "assets/ai-images"
    public_folder: "/assets/ai-images"
    fields:
      - { label: "Image", name: "file", widget: "image" }

  - name: "real_videos"
    label: "Real Videos"
    folder: "uploads/real-videos"
    create: true
    slug: "{{filename}}"
    media_folder: "assets/real-videos"
    public_folder: "/assets/real-videos"
    fields:
      - { label: "Video", name: "file", widget: "file" }

  - name: "ai_videos"
    label: "AI Videos"
    folder: "uploads/ai-videos"
    create: true
    slug: "{{filename}}"
    media_folder: "assets/ai-videos"
    public_folder: "/assets/ai-videos"
    fields:
      - { label: "Video", name: "file", widget: "file" }
